Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false
